### ISSUE TITLE
Help understanding parameter

### ISSUE THREAD

**Issue by dooniem** [osohotwateriot/apyosohotwaterapi#1]
Hi. Am I right assuming whenever you call turn on or off, you set fullUtilizationParam =True?
I can’t seem to find documentation nor understand what this parameter does?
Are “you” a part of the OSO team, or is this just someone who owns a OSO Charge and wants HA integration and is quite skilled at just figuring out stuff?

Not sure if to write in English or Norwegian. You decide.

**Comment by osohotwateriot** [comment]
Hello,

The full utilization parameter is used to specify if the water heater should be turned on/off for one hour or until the maximum/minimum energy levels are reached on the device.

For example: Setting the full utilization parameter to True when turning on the heater will force it to heat the water until the maximum energy levels are reached for the device or you can think of it as heating until the maximum temperature of the device is reached.
Setting the turn on with full utilization = False will force the heater to heat the water for one hour only or until the maximum level is reached.  

The scenario is the same for turn off - prevent the heater from heating until minimum energy is reached or for one hour.

**Comment by osohotwateriot** [comment]
I am closing this issue as there are no new comments for it.
